### ISSUE TITLE
中文版的 Patreon

### ISSUE THREAD

**Issue by egoist** [egojump/notes#7]
Patreon: https://www.patreon.com

Telegram 开发讨论组: 见调查兵团微信群

开发代号: Project 015 😅

技术栈: 

- API: [Prisma](https://www.prisma.io/) (GraphQL + PostgreSQL) _WIP_
- 网页版: Next.js or Nuxt.js
- 手机端: React Native

**Comment by limichange** [comment]
nuxt.js +1
